import re
import sys


if __name__ == '__main__':
    r = re.compile(r'''(?x)
        ^ \$(?P<name>[^;\s]+) \s*:\s* (?P<value>[^;\s]+) \s* ; $
    ''')

    inp_fn = sys.argv[1]
    out_fn = sys.argv[2]

    js_vars = []
    with open(inp_fn) as inp:
        for line in inp:
            if not line.strip() or line.startswith('//'):
                continue

            parsed = r.match(line)
            if not parsed:
                print(f'could not parse line {line!r} in {inp_fn!r} file',
                      file=sys.stderr)
                sys.exit(1)

            name = parsed.group('name')
            val = parsed.group('value')
            if (val.endswith('px')):
                val = val[:-2]

            try:
                val = int(val)
            except (ValueError, TypeError):
                val = repr(val)

            js_vars.append(f'export const {name} = {val};')

    with open(out_fn, 'wt') as f:
        f.write(f'// AUTOGENERATED FROM {inp_fn!r}\n\n\n\n')
        f.write('\n'.join(js_vars))
