require("prismjs/components/prism-clike");
require("prismjs/components/prism-javascript");
require("prismjs/components/prism-typescript");
require("prismjs/components/prism-bash");
require("prismjs/components/prism-python");
require("prismjs/components/prism-graphql");
require("prismjs/components/prism-json");
require("prismjs/components/prism-jsonp");
require("prismjs/components/prism-sql");
require("prismjs/components/prism-plsql");
require("prismjs/components/prism-yaml");
require("prismjs/components/prism-c");
require("prismjs/components/prism-go");
require("prismjs/components/prism-powershell");
require("prismjs/components/prism-jsx");
require("prismjs/components/prism-tsx");
require("prismjs/components/prism-rust");
require("prismjs/components/prism-toml");
require("prismjs/components/prism-csharp");
require("prismjs/components/prism-fsharp");
require("prismjs/components/prism-dart");
require("prismjs/components/prism-java");
require("prismjs/components/prism-kotlin");
require("prismjs/components/prism-scala");
require("prismjs/components/prism-elixir");
require("prismjs/components/prism-xml-doc");
require("prismjs/components/prism-groovy");
require("prismjs/components/prism-docker");

require("./auto-grammars.js");
require("./our-grammars.js");

export {};
